# Generated by Django 3.1.7 on 2021-03-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='id_chef',
            field=models.IntegerField(default=0),
        ),
    ]
